//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeuDeLaVie.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JeuDeLaVie.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app.
        /// </summary>
        public static string AppSaves {
            get {
                return ResourceManager.GetString("AppSaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blinker.gol.
        /// </summary>
        public static string BlinkerFile {
            get {
                return ResourceManager.GetString("BlinkerFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3;3;0,0,0;1,1,1;0,0,0.
        /// </summary>
        public static string BlinkerShape {
            get {
                return ResourceManager.GetString("BlinkerShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to glider.gol.
        /// </summary>
        public static string GliderFile {
            get {
                return ResourceManager.GetString("GliderFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3;3;0,1,0;0,0,1;1,1,1.
        /// </summary>
        public static string GliderShape {
            get {
                return ResourceManager.GetString("GliderShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gun.gol.
        /// </summary>
        public static string GunFile {
            get {
                return ResourceManager.GetString("GunFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 33;21;1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
        ///1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
        ///0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
        ///0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
        ///0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0;
        ///0, 0,  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GunShape {
            get {
                return ResourceManager.GetString("GunShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to saves.
        /// </summary>
        public static string SaveDirectory {
            get {
                return ResourceManager.GetString("SaveDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user.
        /// </summary>
        public static string UserSaves {
            get {
                return ResourceManager.GetString("UserSaves", resourceCulture);
            }
        }
    }
}
